import { Movie } from '../types/movie';
import { Showtime } from '../types/showtime';

export const MOCK_MOVIES: Movie[] = [
  {
    id: 'm-spiderman-2d',
    title: 'Spider-Man: Brand New Day (2D)',
    tagline: 'A fresh chapter in the web-slinger saga.',
    synopsis: 'Peter Parker navigates a brand new chapter filled with unexpected allies, emerging citywide threats, and fresh challenges in this 2D theatrical release.',
    durationMinutes: 135,
    releaseYear: 2026,
    rating: 8.8,
    ageRating: 'PG-13',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    posterUrl: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?q=80&w=800&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?q=80&w=1600&auto=format&fit=crop',
    director: 'Destin Daniel Cretton',
    cast: ['Tom Holland', 'Zendaya', 'Jacob Batalon'],
    isFeatured: true,
  },
  {
    id: 'm-spiderman-3d',
    title: 'Spider-Man: Brand New Day (3D)',
    tagline: 'Feel every swing in immersive 3D.',
    synopsis: 'Experience the high-octane web-slinging spectacle of Spider-Man: Brand New Day in full 3D visual depth with enhanced spatial audio and effects.',
    durationMinutes: 135,
    releaseYear: 2026,
    rating: 9.1,
    ageRating: 'PG-13',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    posterUrl: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?q=80&w=800&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1600&auto=format&fit=crop',
    director: 'Destin Daniel Cretton',
    cast: ['Tom Holland', 'Zendaya', 'Jacob Batalon'],
    isFeatured: true,
  },
  {
    id: 'm-avatar-3',
    title: 'Avatar: Fire and Ash',
    tagline: 'Discover the fire tribe of Pandora.',
    synopsis: 'Jake Sully and Neytiri encounter a new, aggressive clan of Na\'vi known as the Ash People in an uncharted region of Pandora.',
    durationMinutes: 192,
    releaseYear: 2025,
    rating: 8.9,
    ageRating: 'PG-13',
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600&auto=format&fit=crop',
    director: 'James Cameron',
    cast: ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver'],
    isFeatured: true,
  },
  {
    id: 'm-inception-odyssey',
    title: 'Inception: Cosmic Rift',
    tagline: 'The mind is the scene of the crime.',
    synopsis: 'A team of dream operatives embark on a deep-level subconscious extraction mission that threatens the fabric of physical reality.',
    durationMinutes: 156,
    releaseYear: 2026,
    rating: 9.0,
    ageRating: 'PG-13',
    genres: ['Sci-Fi', 'Thriller', 'Action'],
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?q=80&w=1600&auto=format&fit=crop',
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'],
    isFeatured: false,
  },
  {
    id: 'm-dune-prophecy',
    title: 'Dune: Messiah Part 1',
    tagline: 'The desert power demands a reckoning.',
    synopsis: 'Paul Atreides ascends the Emperor\'s throne while facing cosmic conspiracies and religious fervour across the known universe.',
    durationMinutes: 168,
    releaseYear: 2026,
    rating: 9.2,
    ageRating: 'PG-13',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=800&auto=format&fit=crop',
    bannerUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1600&auto=format&fit=crop',
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Florence Pugh'],
    isFeatured: true,
  },
];

export const MOCK_SHOWTIMES: Showtime[] = [
  // Spider-Man: Brand New Day (2D)
  {
    id: 'st-sm2d-1',
    movieId: 'm-spiderman-2d',
    hallId: 'hall-a',
    hallName: 'Theatre A',
    startTime: '19:00',
    date: '2026-08-08',
    format: 'Standard 2D',
    priceUSD: 14.50,
    availableSeatsCount: 42,
  },
  {
    id: 'st-sm2d-2',
    movieId: 'm-spiderman-2d',
    hallId: 'hall-a',
    hallName: 'Theatre A',
    startTime: '22:00',
    date: '2026-08-08',
    format: 'Standard 2D',
    priceUSD: 14.50,
    availableSeatsCount: 18,
  },
  {
    id: 'st-sm2d-3',
    movieId: 'm-spiderman-2d',
    hallId: 'hall-b',
    hallName: 'Theatre B',
    startTime: '20:30',
    date: '2026-08-08',
    format: 'Standard 2D',
    priceUSD: 13.00,
    availableSeatsCount: 55,
  },
  {
    id: 'st-sm2d-4',
    movieId: 'm-spiderman-2d',
    hallId: 'hall-c',
    hallName: 'Theatre C',
    startTime: '16:15',
    date: '2026-08-08',
    format: 'Standard 2D',
    priceUSD: 12.50,
    availableSeatsCount: 30,
  },

  // Spider-Man: Brand New Day (3D)
  {
    id: 'st-sm3d-1',
    movieId: 'm-spiderman-3d',
    hallId: 'hall-imax',
    hallName: 'IMAX Auditorium',
    startTime: '18:00',
    date: '2026-08-08',
    format: 'IMAX 3D',
    priceUSD: 20.00,
    availableSeatsCount: 12,
  },
  {
    id: 'st-sm3d-2',
    movieId: 'm-spiderman-3d',
    hallId: 'hall-imax',
    hallName: 'IMAX Auditorium',
    startTime: '21:30',
    date: '2026-08-08',
    format: 'IMAX 3D',
    priceUSD: 22.00,
    availableSeatsCount: 6,
  },
  {
    id: 'st-sm3d-3',
    movieId: 'm-spiderman-3d',
    hallId: 'hall-dolby',
    hallName: 'Dolby Cinema Screen 1',
    startTime: '19:45',
    date: '2026-08-08',
    format: 'Dolby Cinema',
    priceUSD: 18.50,
    availableSeatsCount: 24,
  },

  // Avatar: Fire and Ash
  {
    id: 'st-av3-1',
    movieId: 'm-avatar-3',
    hallId: 'hall-dolby',
    hallName: 'Dolby Cinema Screen 1',
    startTime: '17:00',
    date: '2026-08-08',
    format: 'Dolby Cinema',
    priceUSD: 19.50,
    availableSeatsCount: 34,
  },
  {
    id: 'st-av3-2',
    movieId: 'm-avatar-3',
    hallId: 'hall-imax',
    hallName: 'IMAX Auditorium',
    startTime: '20:15',
    date: '2026-08-08',
    format: 'IMAX 3D',
    priceUSD: 21.00,
    availableSeatsCount: 15,
  },

  // Inception: Cosmic Rift
  {
    id: 'st-inc-1',
    movieId: 'm-inception-odyssey',
    hallId: 'hall-a',
    hallName: 'Theatre A',
    startTime: '18:30',
    date: '2026-08-08',
    format: 'Standard 2D',
    priceUSD: 15.00,
    availableSeatsCount: 50,
  },
  {
    id: 'st-inc-2',
    movieId: 'm-inception-odyssey',
    hallId: 'hall-b',
    hallName: 'Theatre B',
    startTime: '21:15',
    date: '2026-08-08',
    format: 'Standard 2D',
    priceUSD: 15.00,
    availableSeatsCount: 28,
  },

  // Dune: Messiah Part 1
  {
    id: 'st-dune-1',
    movieId: 'm-dune-prophecy',
    hallId: 'hall-imax',
    hallName: 'IMAX Auditorium',
    startTime: '19:15',
    date: '2026-08-08',
    format: 'IMAX 3D',
    priceUSD: 22.50,
    availableSeatsCount: 9,
  },
  {
    id: 'st-dune-2',
    movieId: 'm-dune-prophecy',
    hallId: 'hall-c',
    hallName: 'Theatre C',
    startTime: '22:15',
    date: '2026-08-08',
    format: 'Standard 2D',
    priceUSD: 16.00,
    availableSeatsCount: 40,
  },
];
